config/routes.rb
Rails.application.routes.draw do
  root to: 'books#top'

  get 'books' => 'books#index', as: 'index_book'

  get 'books/:id' => 'books#show', as: 'book'

  get 'books/:id/edit' => 'books#edit', as: 'edit_book'

  post 'books' => 'books#create'

  patch 'books/:id' => 'books#update', as: 'update_book'

  delete 'books/:id' => 'books#destroy', as:'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top

  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def create
  	@book = Book.new(book_params)
    if @book.save
       flash[:notice] = 'Book was successfully saved.'
  	   redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = 'Book was successfully updated.'
       redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to index_book_path
  end

 private
 def book_params
 	params.require(:book).permit(:title, :body)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="edit-box">
	  <h2>Editing book</h2>
	  <%= form_for(@book) do |f| %>
        <% if @book.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
             <h5 class="error-message"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h5>
             <ul class="error-text">
               <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
               <% end %>
             </ul>
          </div>
        <% end %>
        <div class="field">
          <%= f.label :title, "Title"%>
	        <%= f.text_field :title %>
        </div>
        <div class="field">
          <%= f.label :body, "Body"%>
          <%= f.text_area :body %>
        </div>
        <div><%= f.submit 'Update Book' %></div>
      <% end %>
</div>
<div class="link-box">
    <span><%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", index_book_path %></span>
</div>

app/views/books/index.html.erb
<main class="index-main">
  <h2>Books</h2>

    <table class= "index-table">
      <tr>
        <th>Title</th> <th>Body</th>
      </tr>
      <% @books.each do |b| %>
        <tr>
          <td><%= b.title %></td>
          <td><%= b.body %></td>
          <td><%= link_to "Show", book_path(b.id) %></td>
          <td><%= link_to "Edit", edit_book_path(b.id) %></td>
          <td><%= link_to "Destroy", destroy_book_path(b.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <h3>New Book</h3>
	  <%= form_for(@book) do |f| %>
        <% if @book.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
             <h5 class="error-message"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h5>
             <ul class="error-text">
               <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
               <% end %>
             </ul>
          </div>
        <% end %>
        <div class="field">
          <%= f.label :title, "Title"%>
	        <%= f.text_field :title %>
        </div>
        <div class="field">
          <%= f.label :body, "Body"%>
          <%= f.text_area :body %>
        </div>
        <div><%= f.submit 'Create Book' %></div>
    <% end %>

</main>

app/views/books/show.html.erb
<main class="main-show">
	<% if flash[:notice] %>
	  <div class="flash">
	  	<%= flash[:notice] %>
	  </div>
	<% end %>
	<p class="show-title"><span class="font-bold">Title: </span><%= @book.title %></p>
	<p class="show-body"><span class="font-bold">Body: </span><%= @book.body %></p>
</main>
<div class="link-box">
	<span><%= link_to "Edit", edit_book_path(@book.id) %> | <%= link_to "Back", index_book_path %></span>
</div>

app/views/books/top.html.erb
<h2 class="top-title">ようこそBookersへ!</h2>
<div class="top-box">
    <p class="top-text">
	    <b>Bookers</b> では、 様々な書籍に関するあなたの意見や<br>
                    印象を共有し交換することができます。<br>
                    <%= link_to "start", index_book_path %>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>